### ISSUE TITLE
Databricks built-in Azure AD authentication mechanism does not work

### ISSUE THREAD

**Issue by mlonsk** [TabularEditor/TabularEditor3#1451]
### Description

The Databricks connector has an issue where the built-in Azure AD Authentication mechanism is not working, leading to the Import Table Wizard and Schema Update does not work currently for users using Azure AD Authentication:

![Image](https://github.com/user-attachments/assets/9f140e7d-aced-4858-8fe4-9666d178f54f)

The workaround is that each user needs to create an access token in Databricks and use that in Tabular Editor 3 instead. 

To do this, go to your Azure Databricks workspace, click the profile icon in the top-right corner, and choose "Settings". Then, under the "Developer" tab, click the "Manage" button next to "Access tokens":

![Image](https://github.com/user-attachments/assets/392d225a-5de4-47e8-b26c-654403e02bb0)

Generate a new token for use with Tabular Editor.

In Tabular Editor 3, select the "Access Token" dropdown option and paste the token you generated above:
![Image](https://github.com/user-attachments/assets/743a09f9-b41a-4c70-b745-bf486015885b)

We are actively working on finding a solution and will provide updates when we have any. We appreciate your understanding and patience while we look at how best to solve it.

**Comment by mlonsk** [comment]
We have identified the issue and are working on providing a hotfix for it as soon as possible.

**Comment by otykier** [comment]
Happy to inform our customers that this issue is now fixed in [3.20.1](https://docs.tabulareditor.com/te3/other/release-notes/3_20_1.html?tabs=downloads).

**Comment by bnewman-tech** [comment]
We are still experiencing issues with the Tabular Editor - User delegated access to data sources enterprise application.

Even though the app is configured to use delegated permissions, the authorization flow requires users to be **admins** in order to grant consent, which defeats the purpose of delegated access.

As a Global Admin, I attempted to grant consent on behalf of all users using the "Grant admin consent" button (screenshot attached), but no permissions appear to be granted, and the flow still requires individual user admin privileges to proceed.

This effectively blocks non-admin users from using the app.

Please advise on the correct configuration or if this is a known limitation or bug.

![Image](https://github.com/user-attachments/assets/36954084-f872-4ba9-aed5-6e38d72873ff)

**Comment by otykier** [comment]
@dbojsen can you take a look?

**Comment by DBojsen** [comment]
Hi @bnewman-tech 

It seems we made a mistake when configuring the permissions needed, and left 2 out from the list, which would explain why it keeps reappearing.  The list has been updated and now consists of:

<img width="780" alt="Image" src="https://github.com/user-attachments/assets/619700cc-349b-4674-a8a9-c455d88054aa" />

None of the permissions require admin consent, but this also depends on the configuration of the tenant where consent is needed.

Can you please have a try with the updated permission list and see if it works for you?

**Comment by fluxium** [comment]
> None of the permissions require admin consent, but this also depends on the configuration of the tenant where consent is needed.

Expanding on this a bit for anyone else trying to get this to work. If your tenant has the following set in the user consent settings: 

![Image](https://github.com/user-attachments/assets/520afa6e-1aed-4bda-b126-b197d33fa8f9)

You may need to add additional API permissions (like delegated AzureDatabricks `user_impersonation`) to low impact permission classification on this pane in Entra portal: https://entra.microsoft.com/?feature.msaljs=true#view/Microsoft_AAD_IAM/ConsentPoliciesMenuBlade/~/Permissions

**Comment by mlonsk** [comment]
We have recently published a docs article for how to set up Databricks with Tabular Editor: https://docs.tabulareditor.com/te3/tutorials/connecting-to-azure-databricks.html
