### ISSUE TITLE
Issue with Semantic Analysis Error.

### ISSUE THREAD

**Issue by tobimax** [TabularEditor/TabularEditor3#62]
Hi,

This valid DAX is giving the error - "Only a single column can be used in a scalar predicate filter expression."

```javascript
CALCULATE (
    [Order Lines Unique],
    'Sales Order Lines'[LeadTime DateDiff] = 10
        && (
            'Sales Order Lines'[Customer Requested Shipping Date] <> BLANK ()
                || 'Sales Order Lines'[OrderDate] <> BLANK ()
        ),
    USERELATIONSHIP ( Dates[DateID], 'Sales Order Lines'[DateID_OrderDate] )
)
```

Regards

Toby

**Comment by otykier** [comment]
Hi Toby.

Could you provide the following details:

- Are you connected to an instance of Analysis Services, and if so, what kind? (Power BI Desktop, SSAS 2016/2017/2019, Azure AS, PBI Premium?)
- Screenshot of the "Messages" window that displays the error

By default, Tabular Editor 3 should be able to detect if the syntax with multiple columns in a scalar predicate is allowed or not, based on what semantic engine you are using (For example, it doesn't work with SSAS 2016/2017/2019). But if you're working offline (i.e. by loading a .bim or .pbit file in Tabular Editor), it's not possible to detect the version of the AS engine used, so in that case you can override whether the syntax is allowed under Tools > Preferences > DAX Editor:

![image](https://user-images.githubusercontent.com/8976200/121308244-1c302680-c901-11eb-9975-7d5074c98982.png)

Thanks!

**Comment by tobimax** [comment]
Hi,

I'm connected to a Premium P2 - Gen 2 (and a local PBI model) both show the error. I have played around with different DAX expressions (Nested AND OR vs && || ) and it still shows the error. 

I have tried changing the DAX settings & restarting but I still get the same error.

![image](https://user-images.githubusercontent.com/362244/121946256-4429ea80-cd44-11eb-8329-c777cd0a1f4e.png)

![image](https://user-images.githubusercontent.com/362244/121947617-bcdd7680-cd45-11eb-9d69-c9648a32ec90.png)

Regards

Toby

**Comment by otykier** [comment]
This should now work in [3.0.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.6). At least if you choose the "Always allow multiple columns" option. Could you let me know if the Auto-detect option works as well? Thanks!

**Comment by KamilZet** [comment]
Hi @otykier 

I'm working with .bim file and I choose the "Always allow multiple columns" option. However, I still see the red dots next to the names of the measures that use multiple column in filter sections. Can I somehow disable these error icons when I change the configuration to allow multiple columns?

![image](https://user-images.githubusercontent.com/7767038/122378692-74e96a00-cf66-11eb-835d-268c35481a92.png)

**Comment by otykier** [comment]
@KamilZet did you upgrade to [3.0.6](https://github.com/TabularEditor/TabularEditor3/releases/tag/3.0.6)?

**Comment by KamilZet** [comment]
Yeap, I upgraded today

![image](https://user-images.githubusercontent.com/7767038/122385702-6783ae00-cf6d-11eb-9d2d-fdef0a5d3a43.png)

**Comment by KamilZet** [comment]
@otykier Actually, after resetting my pc, it started to work, i.e. red icons are not anymore visible

**Comment by tobimax** [comment]
Hi Daniel,

Yes, that works great and the auto detect works as well. I have also tested a folder based model in disconnected mode and that also works.

Thanks

Toby.
